version: "3.8"

services:
  syncvault:
    image: ghcr.io/nielheesakkers/syncvault:latest
    container_name: syncvault
    restart: unless-stopped
    ports:
      - "4282:8080"
    volumes:
      - /path/to/syncvault-data:/data
      - /path/to/syncvault-storage:/data/storage
      - /path/to/syncvault-backups:/data/backups
    environment:
      - SYNCVAULT_JWT_SECRET=verander-dit-naar-een-lang-willekeurig-wachtwoord
